In [1]:
#knn算法鸢尾花
#导入算法包以及数据集

import numpy as np 
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
import operator
import random

In [2]:
def knn(x_test, x_data, y_data, k):
    x_data_size = x_data.shape[0]
    #复制
    np.tile(x_test, (x_data_size,1))
    
    diffMat = np.tile(x_test, (x_data_size, 1)) -x_data
    
    sqDiffMat = diffMat ** 2
    sqDistance = sqDiffMat.sum(axis =1)
    distance = sqDistance ** 0.5
    
    sortedDistance = distance.argsort()#sqDistance的索引排序
    classCount = {}
    for i in range(k):
        votelabel = y_data[sortedDistance[i]]
        classCount[votelabel] = classCount.get(votelabel,0) +1
    sortedClassCount = sorted(classCount.items(), key= operator.itemgetter(1),reverse=True)
    return sortedClassCount[0][0]

In [3]:
#载入数据
iris = datasets.load_iris()
#x_train,x_test,y_train,y_test = train_test_split(iris.data,iris.target,test_size = 0.2)
data_size = iris.data.shape[0]
index = [i for i in range(data_size)]   
random.shuffle(index)#打乱
iris.data = iris.data[index]
iris.target = iris.target[index]
                            
                            
#切分数据集
test_size = 40
x_train =  iris.data[test_size:]
x_test = iris.data[:test_size]
y_train = iris.target[test_size:]   
y_test = iris.target[:test_size]
                            
predictions = []
for i in range(x_test.shape[0]):
    predictions.append(knn(x_test[i],x_train,y_train,5))
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.93      0.97        15
           2       0.93      1.00      0.96        13

    accuracy                           0.97        40
   macro avg       0.98      0.98      0.98        40
weighted avg       0.98      0.97      0.98        40



In [4]:
print(confusion_matrix(y_test,predictions))#混淆矩阵

[[12  0  0]
 [ 0 14  1]
 [ 0  0 13]]
